# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title An Rcpp function that constructs a linear regression model
#' @name fastlm
#'
#' @param X numeric vector
#' @param y numeric vector
#'
#' @return numeric scalar
#' @export
#' @useDynLib blblm
#' @importFrom Rcpp sourceCpp
#'
fastLm_impl <- function(X, y) {
    .Call('_blblm_fastLm_impl', PACKAGE = 'blblm', X, y)
}

